---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redmine-config
  namespace: redmine
data:
  REDMINE_DB_USERNAME: testuser
  REDMINE_DB_POSTGRES: database.postgres
  REDMINE_DB_DATABASE: testdatabase
